apiVersion: v1
kind: Service
metadata:
  name: {{ include "aether-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aether-gateway.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- with .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "aether-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.ports.grpc }}
      targetPort: grpc
      protocol: TCP
      appProtocol: grpc
    - name: admin
      port: {{ .Values.ports.admin }}
      targetPort: admin
      protocol: TCP
    - name: ops
      port: {{ .Values.ports.ops }}
      targetPort: ops
      protocol: TCP
