-- Migration 004: First-class task authority lineage fields
-- SQLite counterpart of postgres migration 013_task_authority_lineage.sql.
--
-- The tasks table in 001_full_schema.sql already declares every authority/
-- subject column added by postgres 013:
--   authority_mode, subject_type, subject_id, root_subject_type,
--   root_subject_id, authority_grant_id, root_authority_grant_id,
--   parent_authority_grant_id, authority_audience_type,
--   authority_audience_id, authority_delegate_type, authority_delegate_id
-- The supporting indexes (idx_task_root_authority_grant, idx_task_authority_grant,
-- idx_task_subject) are also already created in 001.
--
-- The postgres migration also runs a one-time UPDATE that backfills these
-- columns from metadata JSON. New aether-lite databases have no pre-existing
-- rows to backfill, and SQLite's json_extract semantics differ enough from
-- postgres's `metadata->>'...'` that emulating the UPDATE is not worth the
-- risk for an empty table — skipped intentionally.

-- Intentionally empty.
