# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sandbox_relay_tunnel.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'sandbox_relay_tunnel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import aether_pb2 as aether__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1asandbox_relay_tunnel.proto\x12\taether.v1\x1a\x0c\x61\x65ther.proto\"\x93\x01\n\x0bTunnelFrame\x12(\n\x02up\x18\x01 \x01(\x0b\x32\x1a.aether.v1.UpstreamMessageH\x00\x12,\n\x04\x64own\x18\x02 \x01(\x0b\x32\x1c.aether.v1.DownstreamMessageH\x00\x12\'\n\x05hello\x18\x03 \x01(\x0b\x32\x16.aether.v1.TunnelHelloH\x00\x42\x03\n\x01\x66\"\x1d\n\x0bTunnelHello\x12\x0e\n\x06tenant\x18\x01 \x01(\t\"\x15\n\x13WatchTenantsRequest\"H\n\x0bTenantEvent\x12\x0e\n\x06tenant\x18\x01 \x01(\t\x12\x0e\n\x06online\x18\x02 \x01(\x08\x12\x19\n\x11snapshot_complete\x18\x03 \x01(\x08\x32\x9c\x01\n\x12SandboxRelayTunnel\x12<\n\x06Tunnel\x12\x16.aether.v1.TunnelFrame\x1a\x16.aether.v1.TunnelFrame(\x01\x30\x01\x12H\n\x0cWatchTenants\x12\x1e.aether.v1.WatchTenantsRequest\x1a\x16.aether.v1.TenantEvent0\x01\x42-Z+github.com/scitrera/aether/api/proto;aetherb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sandbox_relay_tunnel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/scitrera/aether/api/proto;aether'
  _globals['_TUNNELFRAME']._serialized_start=56
  _globals['_TUNNELFRAME']._serialized_end=203
  _globals['_TUNNELHELLO']._serialized_start=205
  _globals['_TUNNELHELLO']._serialized_end=234
  _globals['_WATCHTENANTSREQUEST']._serialized_start=236
  _globals['_WATCHTENANTSREQUEST']._serialized_end=257
  _globals['_TENANTEVENT']._serialized_start=259
  _globals['_TENANTEVENT']._serialized_end=331
  _globals['_SANDBOXRELAYTUNNEL']._serialized_start=334
  _globals['_SANDBOXRELAYTUNNEL']._serialized_end=490
# @@protoc_insertion_point(module_scope)
