# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sandbox_relay_tunnel_pb2 as sandbox__relay__tunnel__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sandbox_relay_tunnel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxRelayTunnelStub:
    """SandboxRelayTunnel is the aggregator's relay-facing surface. A tenant-relay
    sidecar dials Tunnel() and announces its tenant via TunnelHello; the
    aggregator pairs that relay with a provider's AetherGateway.Connect stream
    for the same tenant and splices the two 1:1 (NOT a mux — each pair owns its
    own gateway session, lock, and session id). WatchTenants lets a provider
    learn which tenants currently have an online relay so it can dial in.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Tunnel = channel.stream_stream(
                '/aether.v1.SandboxRelayTunnel/Tunnel',
                request_serializer=sandbox__relay__tunnel__pb2.TunnelFrame.SerializeToString,
                response_deserializer=sandbox__relay__tunnel__pb2.TunnelFrame.FromString,
                _registered_method=True)
        self.WatchTenants = channel.unary_stream(
                '/aether.v1.SandboxRelayTunnel/WatchTenants',
                request_serializer=sandbox__relay__tunnel__pb2.WatchTenantsRequest.SerializeToString,
                response_deserializer=sandbox__relay__tunnel__pb2.TenantEvent.FromString,
                _registered_method=True)


class SandboxRelayTunnelServicer:
    """SandboxRelayTunnel is the aggregator's relay-facing surface. A tenant-relay
    sidecar dials Tunnel() and announces its tenant via TunnelHello; the
    aggregator pairs that relay with a provider's AetherGateway.Connect stream
    for the same tenant and splices the two 1:1 (NOT a mux — each pair owns its
    own gateway session, lock, and session id). WatchTenants lets a provider
    learn which tenants currently have an online relay so it can dial in.
    """

    def Tunnel(self, request_iterator, context):
        """Tunnel carries one provider<->gateway session, framed in both directions.
        The relay's first frame MUST be a TunnelHello announcing its tenant.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchTenants(self, request, context):
        """WatchTenants streams tenant online/offline transitions to a provider.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxRelayTunnelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Tunnel': grpc.stream_stream_rpc_method_handler(
                    servicer.Tunnel,
                    request_deserializer=sandbox__relay__tunnel__pb2.TunnelFrame.FromString,
                    response_serializer=sandbox__relay__tunnel__pb2.TunnelFrame.SerializeToString,
            ),
            'WatchTenants': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchTenants,
                    request_deserializer=sandbox__relay__tunnel__pb2.WatchTenantsRequest.FromString,
                    response_serializer=sandbox__relay__tunnel__pb2.TenantEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aether.v1.SandboxRelayTunnel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aether.v1.SandboxRelayTunnel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxRelayTunnel:
    """SandboxRelayTunnel is the aggregator's relay-facing surface. A tenant-relay
    sidecar dials Tunnel() and announces its tenant via TunnelHello; the
    aggregator pairs that relay with a provider's AetherGateway.Connect stream
    for the same tenant and splices the two 1:1 (NOT a mux — each pair owns its
    own gateway session, lock, and session id). WatchTenants lets a provider
    learn which tenants currently have an online relay so it can dial in.
    """

    @staticmethod
    def Tunnel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/aether.v1.SandboxRelayTunnel/Tunnel',
            sandbox__relay__tunnel__pb2.TunnelFrame.SerializeToString,
            sandbox__relay__tunnel__pb2.TunnelFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchTenants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aether.v1.SandboxRelayTunnel/WatchTenants',
            sandbox__relay__tunnel__pb2.WatchTenantsRequest.SerializeToString,
            sandbox__relay__tunnel__pb2.TenantEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
