// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: aether.proto

package aether

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AetherGateway_Connect_FullMethodName = "/aether.v1.AetherGateway/Connect"
)

// AetherGatewayClient is the client API for AetherGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AetherGatewayClient interface {
	// Bi-directional stream.
	// First message must be InitConnection.
	// Subsequent messages are opaque Envelopes.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UpstreamMessage, DownstreamMessage], error)
}

type aetherGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewAetherGatewayClient(cc grpc.ClientConnInterface) AetherGatewayClient {
	return &aetherGatewayClient{cc}
}

func (c *aetherGatewayClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UpstreamMessage, DownstreamMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AetherGateway_ServiceDesc.Streams[0], AetherGateway_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpstreamMessage, DownstreamMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AetherGateway_ConnectClient = grpc.BidiStreamingClient[UpstreamMessage, DownstreamMessage]

// AetherGatewayServer is the server API for AetherGateway service.
// All implementations must embed UnimplementedAetherGatewayServer
// for forward compatibility.
type AetherGatewayServer interface {
	// Bi-directional stream.
	// First message must be InitConnection.
	// Subsequent messages are opaque Envelopes.
	Connect(grpc.BidiStreamingServer[UpstreamMessage, DownstreamMessage]) error
	mustEmbedUnimplementedAetherGatewayServer()
}

// UnimplementedAetherGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAetherGatewayServer struct{}

func (UnimplementedAetherGatewayServer) Connect(grpc.BidiStreamingServer[UpstreamMessage, DownstreamMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAetherGatewayServer) mustEmbedUnimplementedAetherGatewayServer() {}
func (UnimplementedAetherGatewayServer) testEmbeddedByValue()                       {}

// UnsafeAetherGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AetherGatewayServer will
// result in compilation errors.
type UnsafeAetherGatewayServer interface {
	mustEmbedUnimplementedAetherGatewayServer()
}

func RegisterAetherGatewayServer(s grpc.ServiceRegistrar, srv AetherGatewayServer) {
	// If the following call panics, it indicates UnimplementedAetherGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AetherGateway_ServiceDesc, srv)
}

func _AetherGateway_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AetherGatewayServer).Connect(&grpc.GenericServerStream[UpstreamMessage, DownstreamMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AetherGateway_ConnectServer = grpc.BidiStreamingServer[UpstreamMessage, DownstreamMessage]

// AetherGateway_ServiceDesc is the grpc.ServiceDesc for AetherGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AetherGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aether.v1.AetherGateway",
	HandlerType: (*AetherGatewayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AetherGateway_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "aether.proto",
}
