// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: sandbox_relay_tunnel.proto

package aether

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxRelayTunnel_Tunnel_FullMethodName       = "/aether.v1.SandboxRelayTunnel/Tunnel"
	SandboxRelayTunnel_WatchTenants_FullMethodName = "/aether.v1.SandboxRelayTunnel/WatchTenants"
)

// SandboxRelayTunnelClient is the client API for SandboxRelayTunnel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SandboxRelayTunnel is the aggregator's relay-facing surface. A tenant-relay
// sidecar dials Tunnel() and announces its tenant via TunnelHello; the
// aggregator pairs that relay with a provider's AetherGateway.Connect stream
// for the same tenant and splices the two 1:1 (NOT a mux — each pair owns its
// own gateway session, lock, and session id). WatchTenants lets a provider
// learn which tenants currently have an online relay so it can dial in.
type SandboxRelayTunnelClient interface {
	// Tunnel carries one provider<->gateway session, framed in both directions.
	// The relay's first frame MUST be a TunnelHello announcing its tenant.
	Tunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelFrame, TunnelFrame], error)
	// WatchTenants streams tenant online/offline transitions to a provider.
	WatchTenants(ctx context.Context, in *WatchTenantsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TenantEvent], error)
}

type sandboxRelayTunnelClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxRelayTunnelClient(cc grpc.ClientConnInterface) SandboxRelayTunnelClient {
	return &sandboxRelayTunnelClient{cc}
}

func (c *sandboxRelayTunnelClient) Tunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelFrame, TunnelFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxRelayTunnel_ServiceDesc.Streams[0], SandboxRelayTunnel_Tunnel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TunnelFrame, TunnelFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxRelayTunnel_TunnelClient = grpc.BidiStreamingClient[TunnelFrame, TunnelFrame]

func (c *sandboxRelayTunnelClient) WatchTenants(ctx context.Context, in *WatchTenantsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TenantEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxRelayTunnel_ServiceDesc.Streams[1], SandboxRelayTunnel_WatchTenants_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchTenantsRequest, TenantEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxRelayTunnel_WatchTenantsClient = grpc.ServerStreamingClient[TenantEvent]

// SandboxRelayTunnelServer is the server API for SandboxRelayTunnel service.
// All implementations must embed UnimplementedSandboxRelayTunnelServer
// for forward compatibility.
//
// SandboxRelayTunnel is the aggregator's relay-facing surface. A tenant-relay
// sidecar dials Tunnel() and announces its tenant via TunnelHello; the
// aggregator pairs that relay with a provider's AetherGateway.Connect stream
// for the same tenant and splices the two 1:1 (NOT a mux — each pair owns its
// own gateway session, lock, and session id). WatchTenants lets a provider
// learn which tenants currently have an online relay so it can dial in.
type SandboxRelayTunnelServer interface {
	// Tunnel carries one provider<->gateway session, framed in both directions.
	// The relay's first frame MUST be a TunnelHello announcing its tenant.
	Tunnel(grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]) error
	// WatchTenants streams tenant online/offline transitions to a provider.
	WatchTenants(*WatchTenantsRequest, grpc.ServerStreamingServer[TenantEvent]) error
	mustEmbedUnimplementedSandboxRelayTunnelServer()
}

// UnimplementedSandboxRelayTunnelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxRelayTunnelServer struct{}

func (UnimplementedSandboxRelayTunnelServer) Tunnel(grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]) error {
	return status.Error(codes.Unimplemented, "method Tunnel not implemented")
}
func (UnimplementedSandboxRelayTunnelServer) WatchTenants(*WatchTenantsRequest, grpc.ServerStreamingServer[TenantEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchTenants not implemented")
}
func (UnimplementedSandboxRelayTunnelServer) mustEmbedUnimplementedSandboxRelayTunnelServer() {}
func (UnimplementedSandboxRelayTunnelServer) testEmbeddedByValue()                            {}

// UnsafeSandboxRelayTunnelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxRelayTunnelServer will
// result in compilation errors.
type UnsafeSandboxRelayTunnelServer interface {
	mustEmbedUnimplementedSandboxRelayTunnelServer()
}

func RegisterSandboxRelayTunnelServer(s grpc.ServiceRegistrar, srv SandboxRelayTunnelServer) {
	// If the following call panics, it indicates UnimplementedSandboxRelayTunnelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxRelayTunnel_ServiceDesc, srv)
}

func _SandboxRelayTunnel_Tunnel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SandboxRelayTunnelServer).Tunnel(&grpc.GenericServerStream[TunnelFrame, TunnelFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxRelayTunnel_TunnelServer = grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]

func _SandboxRelayTunnel_WatchTenants_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchTenantsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxRelayTunnelServer).WatchTenants(m, &grpc.GenericServerStream[WatchTenantsRequest, TenantEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxRelayTunnel_WatchTenantsServer = grpc.ServerStreamingServer[TenantEvent]

// SandboxRelayTunnel_ServiceDesc is the grpc.ServiceDesc for SandboxRelayTunnel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxRelayTunnel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aether.v1.SandboxRelayTunnel",
	HandlerType: (*SandboxRelayTunnelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Tunnel",
			Handler:       _SandboxRelayTunnel_Tunnel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "WatchTenants",
			Handler:       _SandboxRelayTunnel_WatchTenants_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sandbox_relay_tunnel.proto",
}
