// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sandbox_relay_tunnel.proto

package aether

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TunnelFrame wraps either direction of a relayed gateway session, or the
// relay's opening hello. Provider->relay carries UpstreamMessage (up);
// relay->provider carries DownstreamMessage (down).
type TunnelFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to F:
	//
	//	*TunnelFrame_Up
	//	*TunnelFrame_Down
	//	*TunnelFrame_Hello
	F             isTunnelFrame_F `protobuf_oneof:"f"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelFrame) Reset() {
	*x = TunnelFrame{}
	mi := &file_sandbox_relay_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelFrame) ProtoMessage() {}

func (x *TunnelFrame) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_relay_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelFrame.ProtoReflect.Descriptor instead.
func (*TunnelFrame) Descriptor() ([]byte, []int) {
	return file_sandbox_relay_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelFrame) GetF() isTunnelFrame_F {
	if x != nil {
		return x.F
	}
	return nil
}

func (x *TunnelFrame) GetUp() *UpstreamMessage {
	if x != nil {
		if x, ok := x.F.(*TunnelFrame_Up); ok {
			return x.Up
		}
	}
	return nil
}

func (x *TunnelFrame) GetDown() *DownstreamMessage {
	if x != nil {
		if x, ok := x.F.(*TunnelFrame_Down); ok {
			return x.Down
		}
	}
	return nil
}

func (x *TunnelFrame) GetHello() *TunnelHello {
	if x != nil {
		if x, ok := x.F.(*TunnelFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

type isTunnelFrame_F interface {
	isTunnelFrame_F()
}

type TunnelFrame_Up struct {
	Up *UpstreamMessage `protobuf:"bytes,1,opt,name=up,proto3,oneof"`
}

type TunnelFrame_Down struct {
	Down *DownstreamMessage `protobuf:"bytes,2,opt,name=down,proto3,oneof"`
}

type TunnelFrame_Hello struct {
	Hello *TunnelHello `protobuf:"bytes,3,opt,name=hello,proto3,oneof"`
}

func (*TunnelFrame_Up) isTunnelFrame_F() {}

func (*TunnelFrame_Down) isTunnelFrame_F() {}

func (*TunnelFrame_Hello) isTunnelFrame_F() {}

// TunnelHello is the relay's opening frame, announcing the tenant it serves.
// The tenant string is a hint that MUST be validated against the relay's
// peer-certificate CN before any pairing.
type TunnelHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelHello) Reset() {
	*x = TunnelHello{}
	mi := &file_sandbox_relay_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelHello) ProtoMessage() {}

func (x *TunnelHello) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_relay_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelHello.ProtoReflect.Descriptor instead.
func (*TunnelHello) Descriptor() ([]byte, []int) {
	return file_sandbox_relay_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *TunnelHello) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

// WatchTenantsRequest carries no parameters; the aggregator streams every
// tenant transition for the lifetime of the call.
type WatchTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTenantsRequest) Reset() {
	*x = WatchTenantsRequest{}
	mi := &file_sandbox_relay_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTenantsRequest) ProtoMessage() {}

func (x *WatchTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_relay_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTenantsRequest.ProtoReflect.Descriptor instead.
func (*WatchTenantsRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_relay_tunnel_proto_rawDescGZIP(), []int{2}
}

// TenantEvent reports a tenant's relay coming online (online=true) or going
// offline (online=false).
//
// snapshot_complete is a terminal sentinel emitted exactly once per
// (re)subscribe, after the burst of currently-online tenants is replayed and
// before any live transitions stream. The provider uses it to deterministically
// prune tenants that left during a watch disconnect (they are absent from the
// replay set). Live events always carry snapshot_complete=false (the zero
// value); the sentinel carries an empty tenant and online is irrelevant.
type TenantEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Tenant           string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Online           bool                   `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	SnapshotComplete bool                   `protobuf:"varint,3,opt,name=snapshot_complete,json=snapshotComplete,proto3" json:"snapshot_complete,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TenantEvent) Reset() {
	*x = TenantEvent{}
	mi := &file_sandbox_relay_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantEvent) ProtoMessage() {}

func (x *TenantEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_relay_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantEvent.ProtoReflect.Descriptor instead.
func (*TenantEvent) Descriptor() ([]byte, []int) {
	return file_sandbox_relay_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *TenantEvent) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *TenantEvent) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *TenantEvent) GetSnapshotComplete() bool {
	if x != nil {
		return x.SnapshotComplete
	}
	return false
}

var File_sandbox_relay_tunnel_proto protoreflect.FileDescriptor

const file_sandbox_relay_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x1asandbox_relay_tunnel.proto\x12\taether.v1\x1a\faether.proto\"\xa4\x01\n" +
	"\vTunnelFrame\x12,\n" +
	"\x02up\x18\x01 \x01(\v2\x1a.aether.v1.UpstreamMessageH\x00R\x02up\x122\n" +
	"\x04down\x18\x02 \x01(\v2\x1c.aether.v1.DownstreamMessageH\x00R\x04down\x12.\n" +
	"\x05hello\x18\x03 \x01(\v2\x16.aether.v1.TunnelHelloH\x00R\x05helloB\x03\n" +
	"\x01f\"%\n" +
	"\vTunnelHello\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\"\x15\n" +
	"\x13WatchTenantsRequest\"j\n" +
	"\vTenantEvent\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x16\n" +
	"\x06online\x18\x02 \x01(\bR\x06online\x12+\n" +
	"\x11snapshot_complete\x18\x03 \x01(\bR\x10snapshotComplete2\x9c\x01\n" +
	"\x12SandboxRelayTunnel\x12<\n" +
	"\x06Tunnel\x12\x16.aether.v1.TunnelFrame\x1a\x16.aether.v1.TunnelFrame(\x010\x01\x12H\n" +
	"\fWatchTenants\x12\x1e.aether.v1.WatchTenantsRequest\x1a\x16.aether.v1.TenantEvent0\x01B-Z+github.com/scitrera/aether/api/proto;aetherb\x06proto3"

var (
	file_sandbox_relay_tunnel_proto_rawDescOnce sync.Once
	file_sandbox_relay_tunnel_proto_rawDescData []byte
)

func file_sandbox_relay_tunnel_proto_rawDescGZIP() []byte {
	file_sandbox_relay_tunnel_proto_rawDescOnce.Do(func() {
		file_sandbox_relay_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_relay_tunnel_proto_rawDesc), len(file_sandbox_relay_tunnel_proto_rawDesc)))
	})
	return file_sandbox_relay_tunnel_proto_rawDescData
}

var file_sandbox_relay_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sandbox_relay_tunnel_proto_goTypes = []any{
	(*TunnelFrame)(nil),         // 0: aether.v1.TunnelFrame
	(*TunnelHello)(nil),         // 1: aether.v1.TunnelHello
	(*WatchTenantsRequest)(nil), // 2: aether.v1.WatchTenantsRequest
	(*TenantEvent)(nil),         // 3: aether.v1.TenantEvent
	(*UpstreamMessage)(nil),     // 4: aether.v1.UpstreamMessage
	(*DownstreamMessage)(nil),   // 5: aether.v1.DownstreamMessage
}
var file_sandbox_relay_tunnel_proto_depIdxs = []int32{
	4, // 0: aether.v1.TunnelFrame.up:type_name -> aether.v1.UpstreamMessage
	5, // 1: aether.v1.TunnelFrame.down:type_name -> aether.v1.DownstreamMessage
	1, // 2: aether.v1.TunnelFrame.hello:type_name -> aether.v1.TunnelHello
	0, // 3: aether.v1.SandboxRelayTunnel.Tunnel:input_type -> aether.v1.TunnelFrame
	2, // 4: aether.v1.SandboxRelayTunnel.WatchTenants:input_type -> aether.v1.WatchTenantsRequest
	0, // 5: aether.v1.SandboxRelayTunnel.Tunnel:output_type -> aether.v1.TunnelFrame
	3, // 6: aether.v1.SandboxRelayTunnel.WatchTenants:output_type -> aether.v1.TenantEvent
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sandbox_relay_tunnel_proto_init() }
func file_sandbox_relay_tunnel_proto_init() {
	if File_sandbox_relay_tunnel_proto != nil {
		return
	}
	file_aether_proto_init()
	file_sandbox_relay_tunnel_proto_msgTypes[0].OneofWrappers = []any{
		(*TunnelFrame_Up)(nil),
		(*TunnelFrame_Down)(nil),
		(*TunnelFrame_Hello)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_relay_tunnel_proto_rawDesc), len(file_sandbox_relay_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_relay_tunnel_proto_goTypes,
		DependencyIndexes: file_sandbox_relay_tunnel_proto_depIdxs,
		MessageInfos:      file_sandbox_relay_tunnel_proto_msgTypes,
	}.Build()
	File_sandbox_relay_tunnel_proto = out.File
	file_sandbox_relay_tunnel_proto_goTypes = nil
	file_sandbox_relay_tunnel_proto_depIdxs = nil
}
