// Original file: aether.proto

import type { IncomingMessage as _aether_v1_IncomingMessage, IncomingMessage__Output as _aether_v1_IncomingMessage__Output } from '../../aether/v1/IncomingMessage';
import type { ConfigSnapshot as _aether_v1_ConfigSnapshot, ConfigSnapshot__Output as _aether_v1_ConfigSnapshot__Output } from '../../aether/v1/ConfigSnapshot';
import type { Signal as _aether_v1_Signal, Signal__Output as _aether_v1_Signal__Output } from '../../aether/v1/Signal';
import type { ErrorResponse as _aether_v1_ErrorResponse, ErrorResponse__Output as _aether_v1_ErrorResponse__Output } from '../../aether/v1/ErrorResponse';
import type { KVResponse as _aether_v1_KVResponse, KVResponse__Output as _aether_v1_KVResponse__Output } from '../../aether/v1/KVResponse';
import type { TaskAssignment as _aether_v1_TaskAssignment, TaskAssignment__Output as _aether_v1_TaskAssignment__Output } from '../../aether/v1/TaskAssignment';
import type { ConnectionAck as _aether_v1_ConnectionAck, ConnectionAck__Output as _aether_v1_ConnectionAck__Output } from '../../aether/v1/ConnectionAck';
import type { CheckpointResponse as _aether_v1_CheckpointResponse, CheckpointResponse__Output as _aether_v1_CheckpointResponse__Output } from '../../aether/v1/CheckpointResponse';
import type { AdminResponse as _aether_v1_AdminResponse, AdminResponse__Output as _aether_v1_AdminResponse__Output } from '../../aether/v1/AdminResponse';
import type { SessionOperationResponse as _aether_v1_SessionOperationResponse, SessionOperationResponse__Output as _aether_v1_SessionOperationResponse__Output } from '../../aether/v1/SessionOperationResponse';
import type { TaskQueryResponse as _aether_v1_TaskQueryResponse, TaskQueryResponse__Output as _aether_v1_TaskQueryResponse__Output } from '../../aether/v1/TaskQueryResponse';
import type { TaskOperationResponse as _aether_v1_TaskOperationResponse, TaskOperationResponse__Output as _aether_v1_TaskOperationResponse__Output } from '../../aether/v1/TaskOperationResponse';
import type { WorkspaceResponse as _aether_v1_WorkspaceResponse, WorkspaceResponse__Output as _aether_v1_WorkspaceResponse__Output } from '../../aether/v1/WorkspaceResponse';
import type { AgentResponse as _aether_v1_AgentResponse, AgentResponse__Output as _aether_v1_AgentResponse__Output } from '../../aether/v1/AgentResponse';
import type { ACLResponse as _aether_v1_ACLResponse, ACLResponse__Output as _aether_v1_ACLResponse__Output } from '../../aether/v1/ACLResponse';
import type { ProgressUpdate as _aether_v1_ProgressUpdate, ProgressUpdate__Output as _aether_v1_ProgressUpdate__Output } from '../../aether/v1/ProgressUpdate';
import type { WorkflowResponse as _aether_v1_WorkflowResponse, WorkflowResponse__Output as _aether_v1_WorkflowResponse__Output } from '../../aether/v1/WorkflowResponse';
import type { WorkflowOperation as _aether_v1_WorkflowOperation, WorkflowOperation__Output as _aether_v1_WorkflowOperation__Output } from '../../aether/v1/WorkflowOperation';
import type { TokenResponse as _aether_v1_TokenResponse, TokenResponse__Output as _aether_v1_TokenResponse__Output } from '../../aether/v1/TokenResponse';
import type { AuditQueryResponse as _aether_v1_AuditQueryResponse, AuditQueryResponse__Output as _aether_v1_AuditQueryResponse__Output } from '../../aether/v1/AuditQueryResponse';
import type { AuthorityGrantResponse as _aether_v1_AuthorityGrantResponse, AuthorityGrantResponse__Output as _aether_v1_AuthorityGrantResponse__Output } from '../../aether/v1/AuthorityGrantResponse';
import type { CreateTaskResponse as _aether_v1_CreateTaskResponse, CreateTaskResponse__Output as _aether_v1_CreateTaskResponse__Output } from '../../aether/v1/CreateTaskResponse';
import type { ProxyHttpResponse as _aether_v1_ProxyHttpResponse, ProxyHttpResponse__Output as _aether_v1_ProxyHttpResponse__Output } from '../../aether/v1/ProxyHttpResponse';
import type { ProxyHttpBodyChunk as _aether_v1_ProxyHttpBodyChunk, ProxyHttpBodyChunk__Output as _aether_v1_ProxyHttpBodyChunk__Output } from '../../aether/v1/ProxyHttpBodyChunk';
import type { TunnelAck as _aether_v1_TunnelAck, TunnelAck__Output as _aether_v1_TunnelAck__Output } from '../../aether/v1/TunnelAck';
import type { TunnelClose as _aether_v1_TunnelClose, TunnelClose__Output as _aether_v1_TunnelClose__Output } from '../../aether/v1/TunnelClose';
import type { TunnelData as _aether_v1_TunnelData, TunnelData__Output as _aether_v1_TunnelData__Output } from '../../aether/v1/TunnelData';
import type { ProxyHttpRequest as _aether_v1_ProxyHttpRequest, ProxyHttpRequest__Output as _aether_v1_ProxyHttpRequest__Output } from '../../aether/v1/ProxyHttpRequest';
import type { ResolveAuthorityResponse as _aether_v1_ResolveAuthorityResponse, ResolveAuthorityResponse__Output as _aether_v1_ResolveAuthorityResponse__Output } from '../../aether/v1/ResolveAuthorityResponse';
import type { ConnectionStatusResponse as _aether_v1_ConnectionStatusResponse, ConnectionStatusResponse__Output as _aether_v1_ConnectionStatusResponse__Output } from '../../aether/v1/ConnectionStatusResponse';
import type { AuthorityGrantRevocation as _aether_v1_AuthorityGrantRevocation, AuthorityGrantRevocation__Output as _aether_v1_AuthorityGrantRevocation__Output } from '../../aether/v1/AuthorityGrantRevocation';
import type { SubmitAuditEventResponse as _aether_v1_SubmitAuditEventResponse, SubmitAuditEventResponse__Output as _aether_v1_SubmitAuditEventResponse__Output } from '../../aether/v1/SubmitAuditEventResponse';

export interface DownstreamMessage {
  'msg'?: (_aether_v1_IncomingMessage | null);
  'config'?: (_aether_v1_ConfigSnapshot | null);
  'signal'?: (_aether_v1_Signal | null);
  'error'?: (_aether_v1_ErrorResponse | null);
  'kv'?: (_aether_v1_KVResponse | null);
  'taskAssignment'?: (_aether_v1_TaskAssignment | null);
  'connectionAck'?: (_aether_v1_ConnectionAck | null);
  'checkpoint'?: (_aether_v1_CheckpointResponse | null);
  'admin'?: (_aether_v1_AdminResponse | null);
  'sessionResponse'?: (_aether_v1_SessionOperationResponse | null);
  'taskQuery'?: (_aether_v1_TaskQueryResponse | null);
  'taskOp'?: (_aether_v1_TaskOperationResponse | null);
  'workspace'?: (_aether_v1_WorkspaceResponse | null);
  'agent'?: (_aether_v1_AgentResponse | null);
  'acl'?: (_aether_v1_ACLResponse | null);
  'progressUpdate'?: (_aether_v1_ProgressUpdate | null);
  'workflowResponse'?: (_aether_v1_WorkflowResponse | null);
  'workflowOp'?: (_aether_v1_WorkflowOperation | null);
  'token'?: (_aether_v1_TokenResponse | null);
  'auditResponse'?: (_aether_v1_AuditQueryResponse | null);
  'authorityGrant'?: (_aether_v1_AuthorityGrantResponse | null);
  'createTask'?: (_aether_v1_CreateTaskResponse | null);
  'proxyHttpResponse'?: (_aether_v1_ProxyHttpResponse | null);
  'proxyHttpBodyChunk'?: (_aether_v1_ProxyHttpBodyChunk | null);
  'tunnelAck'?: (_aether_v1_TunnelAck | null);
  'tunnelClose'?: (_aether_v1_TunnelClose | null);
  'tunnelData'?: (_aether_v1_TunnelData | null);
  'proxyHttpRequest'?: (_aether_v1_ProxyHttpRequest | null);
  'resolveAuthorityResponse'?: (_aether_v1_ResolveAuthorityResponse | null);
  'connectionStatusResponse'?: (_aether_v1_ConnectionStatusResponse | null);
  'authorityGrantRevocation'?: (_aether_v1_AuthorityGrantRevocation | null);
  'submitAuditEventResponse'?: (_aether_v1_SubmitAuditEventResponse | null);
  'payload'?: "msg"|"config"|"signal"|"error"|"kv"|"taskAssignment"|"connectionAck"|"checkpoint"|"admin"|"sessionResponse"|"taskQuery"|"taskOp"|"workspace"|"agent"|"acl"|"progressUpdate"|"workflowResponse"|"workflowOp"|"token"|"auditResponse"|"authorityGrant"|"createTask"|"proxyHttpResponse"|"proxyHttpBodyChunk"|"tunnelAck"|"tunnelClose"|"tunnelData"|"proxyHttpRequest"|"resolveAuthorityResponse"|"connectionStatusResponse"|"authorityGrantRevocation"|"submitAuditEventResponse";
}

export interface DownstreamMessage__Output {
  'msg'?: (_aether_v1_IncomingMessage__Output | null);
  'config'?: (_aether_v1_ConfigSnapshot__Output | null);
  'signal'?: (_aether_v1_Signal__Output | null);
  'error'?: (_aether_v1_ErrorResponse__Output | null);
  'kv'?: (_aether_v1_KVResponse__Output | null);
  'taskAssignment'?: (_aether_v1_TaskAssignment__Output | null);
  'connectionAck'?: (_aether_v1_ConnectionAck__Output | null);
  'checkpoint'?: (_aether_v1_CheckpointResponse__Output | null);
  'admin'?: (_aether_v1_AdminResponse__Output | null);
  'sessionResponse'?: (_aether_v1_SessionOperationResponse__Output | null);
  'taskQuery'?: (_aether_v1_TaskQueryResponse__Output | null);
  'taskOp'?: (_aether_v1_TaskOperationResponse__Output | null);
  'workspace'?: (_aether_v1_WorkspaceResponse__Output | null);
  'agent'?: (_aether_v1_AgentResponse__Output | null);
  'acl'?: (_aether_v1_ACLResponse__Output | null);
  'progressUpdate'?: (_aether_v1_ProgressUpdate__Output | null);
  'workflowResponse'?: (_aether_v1_WorkflowResponse__Output | null);
  'workflowOp'?: (_aether_v1_WorkflowOperation__Output | null);
  'token'?: (_aether_v1_TokenResponse__Output | null);
  'auditResponse'?: (_aether_v1_AuditQueryResponse__Output | null);
  'authorityGrant'?: (_aether_v1_AuthorityGrantResponse__Output | null);
  'createTask'?: (_aether_v1_CreateTaskResponse__Output | null);
  'proxyHttpResponse'?: (_aether_v1_ProxyHttpResponse__Output | null);
  'proxyHttpBodyChunk'?: (_aether_v1_ProxyHttpBodyChunk__Output | null);
  'tunnelAck'?: (_aether_v1_TunnelAck__Output | null);
  'tunnelClose'?: (_aether_v1_TunnelClose__Output | null);
  'tunnelData'?: (_aether_v1_TunnelData__Output | null);
  'proxyHttpRequest'?: (_aether_v1_ProxyHttpRequest__Output | null);
  'resolveAuthorityResponse'?: (_aether_v1_ResolveAuthorityResponse__Output | null);
  'connectionStatusResponse'?: (_aether_v1_ConnectionStatusResponse__Output | null);
  'authorityGrantRevocation'?: (_aether_v1_AuthorityGrantRevocation__Output | null);
  'submitAuditEventResponse'?: (_aether_v1_SubmitAuditEventResponse__Output | null);
  'payload'?: "msg"|"config"|"signal"|"error"|"kv"|"taskAssignment"|"connectionAck"|"checkpoint"|"admin"|"sessionResponse"|"taskQuery"|"taskOp"|"workspace"|"agent"|"acl"|"progressUpdate"|"workflowResponse"|"workflowOp"|"token"|"auditResponse"|"authorityGrant"|"createTask"|"proxyHttpResponse"|"proxyHttpBodyChunk"|"tunnelAck"|"tunnelClose"|"tunnelData"|"proxyHttpRequest"|"resolveAuthorityResponse"|"connectionStatusResponse"|"authorityGrantRevocation"|"submitAuditEventResponse";
}
